import {
  AstroIcon,
  BrainfuckIcon,
  CIcon,
  CLispIcon,
  ClojureIcon,
  CppIcon,
  CSharpIcon,
  CssIcon,
  DockerIcon,
  ElmIcon,
  FantomIcon,
  GoIcon,
  HandlebarsIcon,
  HtmlIcon,
  JavaIcon,
  JavascriptIcon,
  KotlinIcon,
  MakefileIcon,
  MathematicaIcon,
  MintIcon,
  RubyIcon,
  RustIcon,
  ScssIcon,
  ShellIcon,
  SvelteIcon,
  TypescriptIcon,
  VueIcon,
} from "../icons";
import { type QwikJSX } from "@builder.io/qwik";

export const LANGUAGE_ICON_MAPPING: Record<string, QwikJSX.Element> = {
  "c#": <CSharpIcon />,
  "c++": <CppIcon />,
  "common lisp": <CLispIcon />,
  astro: <AstroIcon />,
  brainfuck: <BrainfuckIcon />,
  c: <CIcon />,
  clojure: <ClojureIcon />,
  css: <CssIcon />,
  dockerfile: <DockerIcon />,
  elm: <ElmIcon />,
  fantom: <FantomIcon />,
  go: <GoIcon />,
  handlebars: <HandlebarsIcon />,
  html: <HtmlIcon />,
  java: <JavaIcon />,
  javascript: <JavascriptIcon />,
  kotlin: <KotlinIcon />,
  mathematica: <MathematicaIcon />,
  makefile: <MakefileIcon />,
  mint: <MintIcon />,
  ruby: <RubyIcon />,
  rust: <RustIcon />,
  scss: <ScssIcon />,
  shell: <ShellIcon />,
  svelte: <SvelteIcon />,
  typescript: <TypescriptIcon />,
  vue: <VueIcon />,
};
